version: 2

sources:
  - name: arizona
    description: source tables for adventure works database
    database: arizona_staging
    schema: source
    tables:
      - name: customers
        description: records of customers
      - name: orders
        description: record of sales orders by order line item
      - name: products
        description: record of each product info
      - name: territory
        description: list of sales regions
      - name: product_categories
        description: list of product categories
      - name: product_subcategories
        description: list of product subcategories
      - name: returns
        description: list of product returns
      - name: order_shipping
        description: record of orders processing stages

