version: 2

sources:
  - name: arizona
    description: source tables for adventure works database
    database: arizona_staging
    schema: source
    tables:
      - name: customers
        description: records of customers
      - name: orders
        description: record of sales orders by order line item
      - name: products
        description: record of each product info
      - name: territory
        description: list of sales regions
      - name: product_categories
        description: list of product categories
      - name: product_subcategories
        description: list of product subcategories
      - name: returns
        description: list of product returns

models:
  - name: stg_customers
    description: One record per customer
    columns:
      - name: customer_id
        tests:
          - not_null
          - unique
          
  - name: stg_orders
    columns:
      - name: order_number
        tests:
          - not_null
      - name: customer_id
        tests:
          - not_null
          - relationships:
              to: ref('stg_customers')
              field: customer_id
      - name: product_id
        tests:
          - not_null
          - relationships:
              to: ref('stg_products')
              field: product_id
  
  - name: stg_products
    columns:
      - name: product_id
        tests:
          - unique
          - not_null
  
  - name: stg_territory
    columns:
      - name: territory_id
        tests:
          - unique
          - not_null
  
  - name: stg_product_subcategories
    columns:
      - name: subcategory_id
        tests:
          - unique
          - not_null

  - name: stg_product_categories
    columns:
      - name: category_id
        tests:
          - unique
          - not_null              

  - name: stg_returns
    columns:
      - name: return_date
        tests:
          - not_null
      - name: product_id
        tests:
          - not_null
          - relationships:
              to: ref('stg_products')
              field: product_id
      - name: territory_id
        tests:
          - not_null
          - relationships:
              to: ref('stg_territory')
              field: territory_id


  - name: dim_customers
    description: One record per customer
    columns:
      - name: customer_id
        tests:
          - not_null
          - unique
  
  - name: dim_products
    columns:
      - name: product_id
        tests:
          - unique
          - not_null

  - name: dim_territory
    columns:
      - name: territory_id
        tests:
          - unique
          - not_null 
             